import {Inter} from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFliesBackground from "@/components/FireFliesBackground";
import SoundButton from "@/components/navigation/SoundButton";

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter' //tailwind config
});

export const metadata = {
    title: "My Portfolio Page",
    description: "Generated by create next app",
    openGraph: {
        title: "My Portfolio Page",
        description: "Take a look at my latest projects",
        url: "https://portfolio-page-nextjs.vercel.app/",
        siteName: "My Portfolio Page",
        images: [
            {
                url: "https://myportfolio.com/og-image.png",
                width: 800,
                height: 600,
                alt: "My Portfolio Cover Image",
            },
        ],
        locale: "en_US",
        type: "website",
    },
    icons: {
        icon: "/public/favicon.ico"
    },
    keywords: [
        "portfolio",
        "developer",
        "projects",
        "skills",
        "web development",
        "programming",
    ],
    author: "Tomas Kravcik",
    verification: {
        google: "L5owGN8LdcM7_6gIW"
    },
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={clsx(inter.variable, "bg-background text-foreground font-inter")}>{children}
        <FireFliesBackground/>
        <SoundButton></SoundButton>
        <div id={'modal'}></div>
        </body>
        </html>
    );
}
